export const TIPS = [
  "输入 {highlight}@{/highlight} 后跟文件名可模糊搜索并附加文件到提示词中。",
  "使用 {highlight}!{/highlight} 开头可直接运行 Shell 命令（例如 {highlight}!ls -la{/highlight}）。",
  "按 {highlight}Tab{/highlight} 可在 Build（全权限）和 Plan（只读）Agent 之间切换。",
  "使用 {highlight}/undo{/highlight} 撤销上一条消息及 OpenCode 所做的文件更改。",
  "使用 {highlight}/redo{/highlight} 恢复之前撤销的消息和文件更改。",
  "运行 {highlight}/share{/highlight} 在 opencode.ai 创建当前会话的公开链接。",
  "拖放图片到终端即可将其作为提示词上下文。",
  "按 {highlight}Ctrl+V{/highlight} 可直接从剪贴板粘贴图片。",
  "按 {highlight}Ctrl+X E{/highlight} 或 {highlight}/editor{/highlight} 在外部编辑器中撰写消息。",
  "运行 {highlight}/init{/highlight} 根据代码库结构自动生成项目规则。",
  "运行 {highlight}/models{/highlight} 或 {highlight}Ctrl+X M{/highlight} 查看并切换可用的 AI 模型。",
  "使用 {highlight}/theme{/highlight} 或 {highlight}Ctrl+X T{/highlight} 预览并切换 50+ 种内置主题。",
  "按 {highlight}Ctrl+X N{/highlight} 或 {highlight}/new{/highlight} 开始新的会话。",
  "使用 {highlight}/sessions{/highlight} 或 {highlight}Ctrl+X L{/highlight} 列出并继续之前的会话。",
  "运行 {highlight}/compact{/highlight} 可在接近上下文限制时压缩长会话。",
  "按 {highlight}Ctrl+X X{/highlight} 或 {highlight}/export{/highlight} 将会话保存为 Markdown 文件。",
  "按 {highlight}Ctrl+X Y{/highlight} 将助手的最后一条消息复制到剪贴板。",
  "按 {highlight}Ctrl+P{/highlight} 查看所有可用的操作和命令。",
  "运行 {highlight}/connect{/highlight} 添加支持的 75+ 种 LLM 提供商的 API 密钥。",
  "默认 Leader 键是 {highlight}Ctrl+X{/highlight}；与其他键组合可快速操作。",
  "按 {highlight}F2{/highlight} 快速在最近使用的模型间切换。",
  "按 {highlight}Ctrl+X B{/highlight} 显示/隐藏侧边栏。",
  "使用 {highlight}PageUp{/highlight}/{highlight}PageDown{/highlight} 浏览历史对话。",
  "按 {highlight}Ctrl+G{/highlight} 或 {highlight}Home{/highlight} 跳转到对话开头。",
  "按 {highlight}Ctrl+Alt+G{/highlight} 或 {highlight}End{/highlight} 跳转到最新消息。",
  "按 {highlight}Shift+Enter{/highlight} 或 {highlight}Ctrl+J{/highlight} 输入换行。",
  "输入时按 {highlight}Ctrl+C{/highlight} 清除输入框。",
  "按 {highlight}Escape{/highlight} 中止 AI 生成。",
  "切换到 {highlight}Plan{/highlight} Agent 获取建议而不执行实际更改。",
  "在提示词中使用 {highlight}@<Agent名称>{/highlight} 调用专用子 Agent。",
  "按 {highlight}Ctrl+X Right/Left{/highlight} 在父子会话间切换。",
  "在项目根目录创建 {highlight}opencode.json{/highlight} 进行项目特定设置。",
  "将全局配置放置在 {highlight}~/.config/opencode/opencode.json{/highlight} 中。",
  "添加 {highlight}$schema{/highlight} 到配置中以在编辑器中启用自动补全。",
  "在配置中设置 {highlight}model{/highlight} 以指定默认模型。",
  "通过 {highlight}keybinds{/highlight} 部分覆盖任何按键绑定。",
  "将按键绑定设置为 {highlight}none{/highlight} 可完全禁用它。",
  "在 {highlight}mcp{/highlight} 配置部分设置本地或远程 MCP 服务器。",
  "OpenCode 自动处理需认证远程 MCP 服务器的 OAuth。",
  "添加 {highlight}.md{/highlight} 文件到 {highlight}.opencode/command/{/highlight} 定义可复用的自定义提示词。",
  "在自定义命令中使用 {highlight}$ARGUMENTS{/highlight}、{highlight}$1{/highlight}、{highlight}$2{/highlight} 接收动态输入。",
  "在命令中使用反引号注入 Shell 输出（例如 {highlight}`git status`{/highlight}）。",
  "添加 {highlight}.md{/highlight} 文件到 {highlight}.opencode/agent/{/highlight} 定义专用的 AI 角色。",
  "配置专用 Agent 的 {highlight}edit{/highlight}、{highlight}bash{/highlight} 和 {highlight}webfetch{/highlight} 工具权限。",
  "使用 {highlight}\"git *\": \"allow\"{/highlight} 等模式进行细粒度 Bash 权限控制。",
  "设置 {highlight}\"rm -rf *\": \"deny\"{/highlight} 以阻止破坏性命令。",
  "配置 {highlight}\"git push\": \"ask\"{/highlight} 要求推送前需批准。",
  "OpenCode 使用 prettier、gofmt、ruff 等自动格式化文件。",
  "在配置中设置 {highlight}\"formatter\": false{/highlight} 禁用所有自动格式化。",
  "在配置中定义带有文件扩展名的自定义格式化命令。",
  "OpenCode 使用 LSP 服务器进行智能代码分析。",
  "在 {highlight}.opencode/tool/{/highlight} 创建 {highlight}.ts{/highlight} 文件定义新的 LLM 工具。",
  "工具定义可以调用 Python、Go 等语言编写的脚本。",
  "添加 {highlight}.ts{/highlight} 文件到 {highlight}.opencode/plugin/{/highlight} 用于事件钩子。",
  "使用插件在会话完成时发送系统通知。",
  "创建一个插件防止 OpenCode 读取敏感文件。",
  "使用 {highlight}opencode run{/highlight} 进行非交互式脚本编写。",
  "使用 {highlight}opencode run --continue{/highlight} 恢复上一次会话。",
  "使用 {highlight}opencode run -f file.ts{/highlight} 通过 CLI 附加文件。",
  "使用 {highlight}--format json{/highlight} 获取机器可读的脚本输出。",
  "运行 {highlight}opencode serve{/highlight} 以无头模式 API 访问 OpenCode。",
  "使用 {highlight}opencode run --attach{/highlight} 连接到运行中的服务器以加速运行。",
  "运行 {highlight}opencode upgrade{/highlight} 更新到最新版本。",
  "运行 {highlight}opencode auth list{/highlight} 查看所有已配置的提供商。",
  "运行 {highlight}opencode agent create{/highlight} 进行引导式 Agent 创建。",
  "在 GitHub Issues/PRs 中使用 {highlight}/opencode{/highlight} 触发 AI 操作。",
  "运行 {highlight}opencode github install{/highlight} 设置 GitHub Workflow。",
  "在 issue 上评论 {highlight}/opencode fix this{/highlight} 自动创建 PR。",
  "在 PR 代码行评论 {highlight}/oc{/highlight} 进行针对性代码审查。",
  "使用 {highlight}\"theme\": \"system\"{/highlight} 匹配终端的色彩设置。",
  "在 {highlight}.opencode/themes/{/highlight} 目录创建 JSON 主题文件。",
  "主题支持两种模式的深/浅色变体。",
  "在自定义主题中引用 ANSI 颜色 0-255。",
  "使用 {highlight}{env:VAR_NAME}{/highlight} 语法在配置中引用环境变量。",
  "使用 {highlight}{file:path}{/highlight} 在配置值中包含文件内容。",
  "配置中使用 {highlight}instructions{/highlight} 加载额外的规则文件。",
  "设置 Agent {highlight}temperature{/highlight} 从 0.0（专注）到 1.0（创造性）。",
  "配置 {highlight}maxSteps{/highlight} 限制每个请求的 Agent 迭代次数。",
  "设置 {highlight}\"tools\": {\"bash\": false}{/highlight} 禁用特定工具。",
  "使用 {highlight}\"mcp_*\": false{/highlight} 禁用来自 MCP 服务器的所有工具。",
  "在每个 Agent 配置中覆盖全局工具设置。",
  "设置 {highlight}\"share\": \"auto\"{/highlight} 自动分享所有会话。",
  "设置 {highlight}\"share\": \"disabled\"{/highlight} 禁止任何会话分享。",
  "运行 {highlight}/unshare{/highlight} 取消会话的公开访问。",
  "权限 {highlight}doom_loop{/highlight} 防止无限工具调用循环。",
  "权限 {highlight}external_directory{/highlight} 保护项目外部的文件。",
  "运行 {highlight}opencode debug config{/highlight} 排查配置问题。",
  "使用 {highlight}--print-logs{/highlight} 标志在 stderr 查看详细日志。",
  "按 {highlight}Ctrl+X G{/highlight} 或 {highlight}/timeline{/highlight} 跳转到特定消息。",
  "按 {highlight}Ctrl+X H{/highlight} 切换消息中代码块的可见性。",
  "按 {highlight}Ctrl+X S{/highlight} 或 {highlight}/status{/highlight} 查看系统状态信息。",
  "启用 {highlight}tui.scroll_acceleration{/highlight} 获得类似 macOS 的平滑滚动。",
  "通过命令面板 ({highlight}Ctrl+P{/highlight}) 切换用户名显示。",
  "运行 {highlight}docker run -it --rm ghcr.io/anomalyco/opencode{/highlight} 使用容器化版本。",
  "使用 {highlight}/connect{/highlight} 和 OpenCode Zen 获取精选、测试过的模型。",
  "将项目的 {highlight}AGENTS.md{/highlight} 文件提交到 Git 以供团队共享。",
  "使用 {highlight}/review{/highlight} 审查未提交的更改、分支或 PR。",
  "运行 {highlight}/help{/highlight} 或 {highlight}Ctrl+X H{/highlight} 显示帮助对话框。",
  "使用 {highlight}/details{/highlight} 切换工具执行详情的可见性。",
  "使用 {highlight}/rename{/highlight} 重命名当前会话。",
  "按 {highlight}Ctrl+Z{/highlight} 挂起终端并返回 Shell。",
]
